### ISSUE TITLE
ModuleNotFoundError: No module named 'pyfiglet'

### ISSUE THREAD

**Issue by CWempe** [bgulla/apcupsd-mqtt#2]
Thanks for this image.

But there seems to be an issue.

```console
$ docker logs -f apcupsd-mqtt
Traceback (most recent call last):
  File "/src/apcupsd-mqtt.py", line 9, in <module>
    import pyfiglet
ModuleNotFoundError: No module named 'pyfiglet'
```

I could fix this by adding `pyfiglet` to `requirements.txt`.

Do you want me to create a PR?

**Comment by 877dev** [comment]
Hi @CWempe 

Same issue here, fixed by adding to ```requirements.txt```, thanks for the tip. 
Now having this: 

![image](https://user-images.githubusercontent.com/46575282/109700916-48157080-7b8a-11eb-9477-bd8500c96a79.png)

Curious where you added your mqtt broker settings, direct in `apcupsd-mqtt.py` ?
Seems like there should be an ENV file maybe,

Here's my setup so far:
https://gist.github.com/877dev/58b8b2dc57912eabda79a8acea293df7

**Comment by CWempe** [comment]
I added the settings via environment variables to the container.

See. https://github.com/bgulla/apcupsd-mqtt/blob/master/src/apcupsd-mqtt.py#L22-L29

**Comment by 877dev** [comment]
@CWempe thanks, I'm still learning how to use docker.
Something like this saved as `apcupsd-mqtt.env`?
```
TZ=Europe/London
#MQTT_USER = 
#MQTT_PASSWORD = 
#MQTT_PORT = 1883
#MQTT_HOST = localhost
#INTERVAL = 15
#UPS_ALIAS = socket.gethostname()
#APCUPSD_HOST = 127.0.0.1
#LOG_LEVEL = logging.INFO
```

**Comment by CWempe** [comment]
I am using `docker run` and do not know about an .env file.

It seems to be a valid option.

"Environment variables in Compose | Docker Documentation" https://docs.docker.com/compose/environment-variables/

But i think you need to remove the `#`.

**Comment by 877dev** [comment]
Thank you, I'll keep trying 👍🏻

**Comment by bgulla** [comment]
@CWempe PR's welcome!

**Comment by 877dev** [comment]
@bgulla I don't mind submitting a PR for this one..

Can I ask regarding an error I am having in Portainer logs:
```
Traceback (most recent call last):
  File "/src/apcupsd-mqtt.py", line 98, in <module>
    main()
  File "/src/apcupsd-mqtt.py", line 64, in main
    ups = apc.parse(apc.get(host=APCUPSD_HOST))
  File "/usr/local/lib/python3.9/site-packages/apcaccess/status.py", line 37, in get
    sock.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```

Here are my docker compose settings if you could cast a quick eye over them please:
https://gist.github.com/877dev/58b8b2dc57912eabda79a8acea293df7

PS - my new BX1400UI is damaged on arrival, so I am testing this on an old BX900, I believe the software is the same though...

**Comment by CWempe** [comment]
@877dev 

It looks like you did not change any value of the settings.

1. I am not sure `socket.gethostname()` works if you define it yourself outside the source code.
2. If you use the default settings I do not think you even need to set these.  
  Have you tried without `apcupsd-mqtt.env`?

**Comment by 877dev** [comment]
@CWempe I just tried without `apcupsd-mqtt.env` and rebuilt, still same error.
I'm connecting to the APC via USB connection, maybe something there I need to do?

**Comment by CWempe** [comment]
You are aware you need to run a separate [apcupsd](http://www.apcupsd.org/)?

This docker container only is a bridge between the aspupsd and an mqtt broker.

**Comment by 877dev** [comment]
Erm.. nope!
That is likely a contributing factor 😄 

I suppose there are other ways to bridge apcupsd to mqtt as well then..
